Create government.md
hrazi/azure-docs pull request #1
Opened 2022-05-07 02:55 UTC by hrazi

2022-06-01 20:47 UTC, ProbablePrime requested changes
You'll need to edit the toc.yml file in the root of our folder to add a table of contents item for this file. 

Otherwise, mild wording change to navigate around the removal of the abbreviations.

2022-06-01 20:47 UTC, ProbablePrime commented on articles/communication-services/concepts/government.md
> +Azure Communication Services (ACS) in [Azure Government](https://azure.microsoft.com/en-us/global-infrastructure/government/) provides compliance with US government requirements for cloud services. I
```suggestion
Azure Communication Services can be used within [Azure Government](https://azure.microsoft.com/en-us/global-infrastructure/government/) to provide compliance with US government requirements for cloud services. In addition to enjoying the features and capabilities of Messaging, Voice and Video calling, developers benefit from the following features that are unique to Azure Government:
```

2022-06-01 20:47 UTC, ProbablePrime commented on articles/communication-services/concepts/government.md
> +Azure Communication Services (ACS) in [Azure Government](https://azure.microsoft.com/en-us/global-infrastructure/government/) provides compliance with US government requirements for cloud services. I
We should never abbreviate ACS according to branding.

2022-06-06 13:55 UTC, hrazi commented
#sign-off

2022-06-06 13:55 UTC, merged